"""update adding member.

Revision ID: 12bba58ac69c
Revises: 19f2106e4f76
Create Date: 2022-10-13 14:42:14.683368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12bba58ac69c'
down_revision = '19f2106e4f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fonctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fonction_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fonction_name')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_name')
    )
    op.create_table('typestructures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_sturcture_name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['typestructures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_sturcture_name')
    )
    op.create_index(op.f('ix_typestructures_parent_id'), 'typestructures', ['parent_id'], unique=False)
    op.create_table('departements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('departement_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departement_name')
    )
    op.create_table('typeStructure_fonction',
    sa.Column('typestructure_id', sa.Integer(), nullable=False),
    sa.Column('fonction_id', sa.Integer(), nullable=False),
    sa.Column('nombre_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fonction_id'], ['fonctions.id'], ),
    sa.ForeignKeyConstraint(['typestructure_id'], ['typestructures.id'], ),
    sa.PrimaryKeyConstraint('typestructure_id', 'fonction_id')
    )
    op.create_table('arrondissements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=False),
    sa.Column('arrondissement_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arrondissement_name')
    )
    op.create_table('structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sturcture_name', sa.String(), nullable=False),
    sa.Column('structure_adresse', sa.String(), nullable=True),
    sa.Column('structure_contacts', sa.String(), nullable=False),
    sa.Column('nombre_communicant', sa.Integer(), nullable=True),
    sa.Column('nombre_baptise', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('typestructure_id', sa.Integer(), nullable=False),
    sa.Column('arrondissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arrondissement_id'], ['arrondissements.id'], ),
    sa.ForeignKeyConstraint(['typestructure_id'], ['typestructures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sturcture_name')
    )
    op.create_table('actualites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('medias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('path_name', sa.String(), nullable=False),
    sa.Column('type_media', sa.Enum('IMAGE', 'VIDEO', 'DOC', name='mediaTypes'), server_default='IMAGE', nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name'),
    sa.UniqueConstraint('path_name')
    )
    op.create_table('programmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('statistiques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_baptise', sa.Integer(), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=4), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('nombre_consacre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_fullname', sa.String(), nullable=False),
    sa.Column('membre_genre', sa.Enum('M', 'F', name='genreTypes'), server_default='M', nullable=False),
    sa.Column('membre_dob', sa.DateTime(), nullable=False),
    sa.Column('membre_pob', sa.String(), nullable=False),
    sa.Column('membre_mother', sa.String(), nullable=False),
    sa.Column('membre_father', sa.String(), nullable=False),
    sa.Column('status_matrimonial', sa.Enum('M', 'C', 'V', name='maritalTypes'), server_default='C', nullable=False),
    sa.Column('membre_conjoint', sa.String(), nullable=False),
    sa.Column('membre_nbenfant', sa.Integer(), nullable=False),
    sa.Column('membre_adresse', sa.String(), nullable=False),
    sa.Column('membre_contacts', sa.String(), nullable=False),
    sa.Column('date_consecration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('typestructure_id', sa.Integer(), nullable=False),
    sa.Column('arrondissement_id', sa.Integer(), nullable=False),
    sa.Column('paroisse_consecration_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arrondissement_id'], ['arrondissements.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], ),
    sa.ForeignKeyConstraint(['paroisse_consecration_id'], ['structures.id'], ),
    sa.ForeignKeyConstraint(['typestructure_id'], ['typestructures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membre_fullname')
    )
    op.create_table('structuremembres',
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('actuel', sa.Boolean(), nullable=False),
    sa.Column('date_affectation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fonction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fonction_id'], ['fonctions.id'], ),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('structure_id', 'membre_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structuremembres')
    op.drop_table('membres')
    op.drop_table('statistiques')
    op.drop_table('programmations')
    op.drop_table('medias')
    op.drop_table('actualites')
    op.drop_table('structures')
    op.drop_table('arrondissements')
    op.drop_table('typeStructure_fonction')
    op.drop_table('departements')
    op.drop_index(op.f('ix_typestructures_parent_id'), table_name='typestructures')
    op.drop_table('typestructures')
    op.drop_table('regions')
    op.drop_table('fonctions')
    # ### end Alembic commands ###
